version: '3'
services:
  ros2_system:
    build: .
    container_name: ros2_container
    network_mode: "host"  # Allows ROS 2 nodes to communicate without additional network setup
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_CONFIG_FILE=config/config1.yaml  # Allows dynamic configuration selection
    volumes:
      - ./:/ros2_ws  # Mounts the entire project directory into the container
    restart: unless-stopped  # Automatically restarts the container if it crashes
    tty: true  # Keeps the terminal session active for debugging
