version: '3'
services:
  ros2_system:
    build: .
    container_name: ros2_container
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_CONFIG_FILE=config/config1.yaml  # 실행할 설정 파일 지정 가능
    volumes:
      - ./:/ros2_ws  # 프로젝트 전체를 컨테이너에서 접근 가능
    restart: unless-stopped  # 예기치 않은 종료 시 자동 재시작
    tty: true  # 터미널에서 로그 유지
