# Request (Input values)
# Image data received from the camera module for processing.
sensor_msgs/Image image_data

---
# Response (Output values)
# Indicates whether the image was successfully processed.
bool processed
# A message providing additional details about the processing result.
string message
