nodes:
  - module: camera_module
    name: camera_type2
    id: "cam_002"
    topics:
      publish: "/camera2/image_raw"
      subscribe: "/camera2/request"
  - module: image_processing_module
    name: processor_type2
    id: "proc_002"
    topics:
      subscribe: "/camera2/image_raw"
      publish: "/image_processing/result2"
    services:
      process: "/image_processing/process_image2"
  - module: robot_module
    name: robot_type2
    id: "robot_002"
    topics:
      subscribe: "/image_processing/result2"
      publish: "/robot/status2"
    actions:
      execute_motion: "/robot/execute_motion2"
